### ISSUE TITLE
Session-scoped async providers can't use async context managers

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/aiodine#16]
**Expected behavior**

An async generator provider should be able to use an async context manager (`async with` syntax).

**Actual behavior**

A `RuntimeError` is thrown when trying to do this.

**To Reproduce**

```python
import asyncio
from contextlib import asynccontextmanager
import aiodine

@asynccontextmanager
async def ctx():
    yield

@aiodine.provider(scope="session")
async def some_value():
    async with ctx():
        yield "value"

@aiodine.consumer
async def main(some_value):
    print("value:", some_value)

asyncio.run(main())
```

**Material**

```
$ python debug/app.py                                                       
value: value
an error occurred during closing of asynchronous generator <async_generator object some_value at 0x10d308488>
asyncgen: <async_generator object some_value at 0x10d308488>
Traceback (most recent call last):
  File "debug/app.py", line 15, in some_value
    yield "value"
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "debug/app.py", line 15, in some_value
    yield "value"
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 189, in __aexit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()
```

**Possible solutions**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
- Python version: 3.7.2
 - aiodine version: 1.2.5

**Additional context**

Ran into this while trying to [integrate orm in a Bocadillo app](https://bocadilloproject.github.io/how-to/orm.html#setup): it needs an async session-scoped provider which calls `async with` on the `Database` instance.

**Comment by florimondmanca** [comment]
Actually, this behavior is caused by not using `async with aiodine.session()`.
